export const data = [
  {
    like: true,
    name: "Сказочное заморское яство",
    title: "Нямушка",
    taste: "с фуа-гра",
    portions: "10 ",
    gift: "1",
    isHappy: false,
    borderColor: "#1698d9",
    weight: "0,5",
    quantity: 2,
    messageDefault: "Чего сидишь? Порадуй котэ ",
    messageDisabled: "Печалька с курой закончился",
    messageSelected: "Печень утки разварная с артишоками",
  },
  {
    like: true,
    name: "Сказочное заморское яство",
    title: "Нямушка",
    taste: "с рыбой",
    portions: "40 ",
    gift: "2 ",
    isHappy: false,
    borderColor: "#d91667",
    weight: "2",
    messageDefault: "Чего сидишь? Порадуй котэ ",
    messageDisabled: "Печалька с курой закончился",
    messageSelected: "Головы щучьи с чесноком да свежайшая сёмгушка",
    quantity: 5,
  },
  {
    like: false,
    name: "Котэ не одобряет?",
    title: "Нямушка",
    taste: "с курой",
    portions: "10 ",
    gift: "5 ",
    isHappy: true,
    borderColor: "#1698d9",
    weight: "5",
    messageDefault: "Чего сидишь? Порадуй котэ ",
    messageDisabled: "Печалька с курой закончился",
    messageSelected: "Филе из циплят с трюфелями в бульоне",
    quantity: 0,
  },
];
